### ISSUE TITLE
Subroutine signatures require Perl 5.20+

### ISSUE THREAD

**Issue by eserte** [kiwiroy/mojo-transaction-http-role-mechanize#2]
Tests fail for older perls (5.18.4 and older):
```
#   Failed test 'use Mojo::DOM::Role::Form'
#   at t/00-basic.t line 29.
# Subroutine signatures require Perl 5.20+ at /home/cpansand/.cpan/build/2019072310/Mojo-Transaction-HTTP-Role-Mechanize-0.01-sUJlsn/blib/lib/Mojo/DOM/Role/Form.pm line 3.
# BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2019072310/Mojo-Transaction-HTTP-Role-Mechanize-0.01-sUJlsn/blib/lib/Mojo/DOM/Role/Form.pm line 3.
# Compilation failed in require at (eval 9) line 1.
# BEGIN failed--compilation aborted at (eval 9) line 1.
# Looks like you failed 1 test of 10.
t/00-basic.t ... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/10 subtests 
... (etc) ...
```

**Comment by kiwiroy** [comment]
Thanks for these two.

**Comment by Tekki** [comment]
@kiwiroy Isn't it boring when you can't use signatures? My very personal opinion is that for new module it's enough to support Perl back to 5.24.

**Comment by kiwiroy** [comment]
@Tekki when Travis turns off trusty, 5.22 will be the minimum available there and will be a big motivator not to test >5 year old versions.

**Comment by Tekki** [comment]
@kiwiroy It's not just about Travis, but about the CPAN testers too. If you don't limit the version in `cpanfile` (will be added to `Makefile.PL` by app::git::ship) they test [on all available versions](http://matrix.cpantesters.org/?dist=Mojo-Transaction-HTTP-Role-Mechanize+0.02). And I'm not sure about Travis. Mojolicious is tested on 5.10 too, so it seems this version is still around. Look at [the tests for your PR](https://github.com/mojolicious/mojo/pull/1387/checks?check_run_id=174239623).

**Comment by kiwiroy** [comment]
@Tekki see travis-ci/perl-builder#8 for details on xenial and <5.22. I'll hold off for the moment with this.

https://github.com/kiwiroy/mojo-transaction-http-role-mechanize/blob/0b11370fec4f32d76822702625b1120dea534242/cpanfile#L2
