### ISSUE TITLE
Version 0.05

### ISSUE THREAD

**Issue by Tekki** [kiwiroy/mojo-transaction-http-role-mechanize#8]
Will version 0.05 ever get published? I still have to use HTML::Form and LWP::UserAgent.

**Comment by kiwiroy** [comment]
Sorry for the delay.
[![Done](https://badge.fury.io/pl/Mojo-Transaction-HTTP-Role-Mechanize.svg)](https://metacpan.org/release/Mojo-Transaction-HTTP-Role-Mechanize)
